In [1]:
import pandas as pd

In [3]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,0.0385
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,0.6630
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,0.8610
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,3.8700
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,0.1710
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,0.1850
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,0.2810
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-13,1781308801,0.2810

In [5]:
pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 11.4 MB/s eta 0:00:01
     ----- ---------------------------------- 1.6/11.9 MB 4.4 MB/s eta 0:00:03
     ------- -------------------------------- 2.1/11.9 MB 3.9 MB/s eta 0:00:03
     ----------- ---------------------------- 3.4/11.9 MB 4.3 MB/s eta 0:00:02
     ------------- -------------------------- 3.9/11.9 MB 3.9 MB/s eta 0:00:03
     -------------- ------------------------- 4.2/11.9 MB 3.8 MB/s eta 0:00:03
     --------------- ------------------------ 4.7/11.9 MB 3.5 MB/s eta 0:00:03
     ----------------- ---------------------- 5.2/11.9 MB 3.3 MB/s eta 0:00:03
     ------------------- -------------------- 5.8/11.9 MB 3.2 MB/s eta 0:00:02
     --------------------- ------------------ 6.3/11.9 MB 3.2 MB/s eta 0:00:02
     ----------------------- ---------------- 6.8/11.9 MB 3.0 MB/s eta 0:00:02
     ------------------------ --------------- 7.3/11.9 MB 3.0 MB/s eta 0:00:02
     -------------------------- ------------- 7.9/11.9 MB 3.0 MB/s eta 0:00:02
     ---------------------------- ----------- 8.4/11.9 MB 2.9 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 2.9 MB/s eta 0:00:02
     ------------------------------- -------- 9.4/11.9 MB 2.9 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 2.7 MB/s eta 0:00:01
     --------------------------------- ------ 10.0/11.9 MB 2.7 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 2.7 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 2.6 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.6 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.6 MB/s  0:00:04
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp310-cp310-win_amd64.whl size=248050 sha256=bc213516d482ac5f3f8b552ae5a36772168c983848c47abec7962d714412d31c
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\76\48\9b\da67ff1a18fe8e9d428f9b1a177716d4a7d363d2bbe83bf6cf
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\mysql\connector\abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':
C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\mysql\connector\abstracts.py:130: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if group is 'connector_python':

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

: