In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\Lenovo\\OneDrive\\Desktop\\Machine_learning\\cars (1).csv")

In [6]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

One hot encoding using pandas

In [8]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

k-1 one hot encoding

In [10]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=True)

In [18]:
x_train.shape

(6502, 4)

In [19]:
x_train.head()

        brand  km_driven    fuel         owner
1939    Honda     100000  Diesel  Second Owner
5455   Maruti     120000  Diesel  Second Owner
7079  Renault     100000  Diesel  Second Owner
2000    Honda      80000  Petrol  Second Owner
1578    Honda      56494  Petrol   First Owner

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [24]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']])

In [25]:
x_trainn_new=ohe.fit_transform(x_test[['fuel','owner']])

In [27]:
x_train_new.shape

(6502, 7)

In [35]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Honda', 100000, 1, ..., 1, 0, 0],
       ['Maruti', 120000, 1, ..., 1, 0, 0],
       ['Renault', 100000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 70000, 0, ..., 0, 0, 0],
       ['Maruti', 110000, 1, ..., 1, 0, 0],
       ['Maruti', 65755, 0, ..., 0, 0, 0]], dtype=object)

one hot encoding with top catogaries

In [36]:
count=df['brand'].value_counts()

In [37]:
df['brand'].nunique()
threshold = 100

In [39]:
repl = count[count <= threshold].index

In [40]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2921,False,False,True,False,False,False,False,False,False,False,False,False,False
2752,False,False,False,False,True,False,False,False,False,False,False,False,False
988,False,False,False,False,True,False,False,False,False,False,False,False,False
3770,False,False,False,False,False,False,False,False,True,False,False,False,False
4890,False,False,False,False,False,False,True,False,False,False,False,False,False